name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  hello-world:
    name: hello-world
    runs-on: ubuntu-20.04

    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !
    
  unit-test:
    name: unit_test
    runs-on: ubuntu-20.04
    container: epitest-docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit-tests
        run: make tests_run

      - name: Run coverage
        run: make coverage