name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  hello-world:
    name: hello-world
    runs-on: ubuntu-20.04

    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !
    
  unit-test:
    name: unit_test
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit-tests
        run: make tests_run

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: ./tests_output.txt