name: Tests

on:
  push:
    branches:
      - main
      - dev2

jobs:
  unit-test:
    container: epitest-docker

    name: unit-test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run unit_tests
      - run: make tests_run

      - name: run coverage
      - run: make coverage