name: Tests

on:
  push
    branches:
      - dev
      - main
      - dev2

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: hello-world
        run : echo "Welcome to the Github Actions workshop !"
